allowBuilds:
  "@prisma/engines": true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@hono/node-server@1.19.13'
  - postcss@8.5.10
overrides:
  '@hono/node-server@<1.19.13': ^1.19.13
  postcss@<8.5.10: ^8.5.10
